export const countries = [
    "Bangladesh",
    "Saudi Arabia",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "India",
    "Pakistan",
    "Malaysia",
    "Indonesia",
    "Turkey",
    "Canada",
    "Australia",
    "Qatar",
    "Kuwait",
    "Oman",
    "Bahrain",
    "Singapore",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "South Africa",
    "Egypt",
    "Morocco",
    "Algeria",
    "Tunisia",
    "Libya",
    "Jordan",
    "Lebanon",
    "Palestine",
    "Syria",
    "Iraq",
    "Yemen",
    "Afghanistan",
    "Iran",
    "China",
    "Japan",
    "South Korea",
    "Russia",
    "Brazil",
    "Argentina",
    "Mexico",
    "Nigeria",
    "Kenya",
    "Somalia",
    "Sudan",
    "Ethiopia"
].sort();

// Common cities for quick selection (optional, can be expanded)
export const commonCities: Record<string, string[]> = {
    "Bangladesh": ["Dhaka", "Chittagong", "Sylhet", "Rajshahi", "Khulna", "Barishal", "Rangpur", "Mymensingh", "Comilla", "Narayanganj"],
    "Saudi Arabia": ["Makkah", "Madinah", "Riyadh", "Jeddah", "Dammam"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Leeds"],
    "United States": ["New York", "Chicago", "Houston", "Los Angeles", "Philadelphia"],
    "India": ["New Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore", "Hyderabad"],
    "Pakistan": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi"]
};
