/**
 * Quiz Questions Seed Script
 * Run: npx tsx prisma/seeds/quizQuestions.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
    // ─── QURAN ───
    {
        questionBn: "পবিত্র কুরআনে মোট কতটি সূরা আছে?",
        questionEn: "How many Surahs (chapters) are there in the Holy Quran?",
        optionsBn: ["১১২টি", "১১৪টি", "১১৬টি", "১১৮টি"],
        optionsEn: ["112", "114", "116", "118"],
        correctIndex: 1,
        explanationBn: "পবিত্র কুরআনে মোট ১১৪টি সূরা রয়েছে।",
        explanationEn: "The Holy Quran contains exactly 114 Surahs.",
        category: "quran",
        difficulty: "easy",
    },
    {
        questionBn: "কুরআনের সবচেয়ে বড় সূরা কোনটি?",
        questionEn: "Which is the longest Surah in the Quran?",
        optionsBn: ["সূরা আল-ইমরান", "সূরা আন-নিসা", "সূরা আল-বাকারা", "সূরা আল-মায়েদা"],
        optionsEn: ["Surah Al-Imran", "Surah An-Nisa", "Surah Al-Baqarah", "Surah Al-Ma'idah"],
        correctIndex: 2,
        explanationBn: "সূরা আল-বাকারা কুরআনের সবচেয়ে বড় সূরা, এতে ২৮৬টি আয়াত রয়েছে।",
        explanationEn: "Surah Al-Baqarah is the longest Surah with 286 verses.",
        category: "quran",
        difficulty: "easy",
    },
    {
        questionBn: "কুরআনের সবচেয়ে ছোট সূরা কোনটি?",
        questionEn: "Which is the shortest Surah in the Quran?",
        optionsBn: ["সূরা আল-ফাতিহা", "সূরা আল-ইখলাস", "সূরা আল-কাউসার", "সূরা আল-আসর"],
        optionsEn: ["Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-Kawthar", "Surah Al-Asr"],
        correctIndex: 2,
        explanationBn: "সূরা আল-কাউসারে মাত্র ৩টি আয়াত রয়েছে, এটিই কুরআনের সবচেয়ে ছোট সূরা।",
        explanationEn: "Surah Al-Kawthar has only 3 verses, making it the shortest Surah.",
        category: "quran",
        difficulty: "easy",
    },
    {
        questionBn: "কুরআনের কোন সূরায় বিসমিল্লাহ দুইবার আছে?",
        questionEn: "In which Surah of the Quran does Bismillah appear twice?",
        optionsBn: ["সূরা আন-নামল", "সূরা আল-বাকারা", "সূরা ইয়াসীন", "সূরা আর-রহমান"],
        optionsEn: ["Surah An-Naml", "Surah Al-Baqarah", "Surah Ya-Sin", "Surah Ar-Rahman"],
        correctIndex: 0,
        explanationBn: "সূরা আন-নামলে দুইবার বিসমিল্লাহ আছে — একবার শুরুতে এবং একবার আয়াত ৩০-এ হযরত সুলাইমান (আ)-এর চিঠিতে।",
        explanationEn: "Surah An-Naml has Bismillah twice — once at the beginning and once in verse 30 in the letter of Prophet Sulayman (AS).",
        category: "quran",
        difficulty: "normal",
    },
    {
        questionBn: "কুরআনের 'কুরসি' আয়াতটি কোন সূরায় আছে?",
        questionEn: "In which Surah is Ayatul Kursi located?",
        optionsBn: ["সূরা আল-ইমরান", "সূরা আল-বাকারা", "সূরা আন-নিসা", "সূরা আল-ফাতিহা"],
        optionsEn: ["Surah Al-Imran", "Surah Al-Baqarah", "Surah An-Nisa", "Surah Al-Fatihah"],
        correctIndex: 1,
        explanationBn: "আয়াতুল কুরসি সূরা আল-বাকারার ২৫৫ নম্বর আয়াত।",
        explanationEn: "Ayatul Kursi is the 255th verse of Surah Al-Baqarah.",
        category: "quran",
        difficulty: "easy",
    },
    {
        questionBn: "কুরআনের কোন সূরাকে 'কুরআনের হৃদয়' বলা হয়?",
        questionEn: "Which Surah is called the 'Heart of the Quran'?",
        optionsBn: ["সূরা আল-ফাতিহা", "সূরা আল-বাকারা", "সূরা ইয়াসীন", "সূরা আল-ইখলাস"],
        optionsEn: ["Surah Al-Fatihah", "Surah Al-Baqarah", "Surah Ya-Sin", "Surah Al-Ikhlas"],
        correctIndex: 2,
        explanationBn: "সূরা ইয়াসীনকে কুরআনের হৃদয় বলা হয়। (সূত্র: তিরমিযী)",
        explanationEn: "Surah Ya-Sin is called the heart of the Quran. (Tirmidhi)",
        category: "quran",
        difficulty: "normal",
    },
    {
        questionBn: "কুরআনে মোট কতটি পারা (জুয) আছে?",
        questionEn: "How many Juz (parts) are in the Quran?",
        optionsBn: ["২৫টি", "২৮টি", "৩০টি", "৩২টি"],
        optionsEn: ["25", "28", "30", "32"],
        correctIndex: 2,
        explanationBn: "কুরআন মোট ৩০টি পারায় বিভক্ত।",
        explanationEn: "The Quran is divided into 30 Juz (parts).",
        category: "quran",
        difficulty: "easy",
    },
    {
        questionBn: "কুরআনে কতটি সিজদার আয়াত রয়েছে?",
        questionEn: "How many verses of prostration (Sajdah) are in the Quran?",
        optionsBn: ["১২টি", "১৪টি", "১৫টি", "১৬টি"],
        optionsEn: ["12", "14", "15", "16"],
        correctIndex: 1,
        explanationBn: "কুরআনে মোট ১৪টি সিজদার আয়াত রয়েছে (হানাফি মতে)।",
        explanationEn: "There are 14 verses of prostration in the Quran (according to Hanafi school).",
        category: "quran",
        difficulty: "hard",
    },

    // ─── SEERAH (Prophet's Biography) ───
    {
        questionBn: "রাসূল (ﷺ) কোন বছর জন্মগ্রহণ করেন?",
        questionEn: "In which year was the Prophet Muhammad (ﷺ) born?",
        optionsBn: ["৫৫০ খ্রিস্টাব্দ", "৫৬৩ খ্রিস্টাব্দ", "৫৭০ খ্রিস্টাব্দ", "৫৮০ খ্রিস্টাব্দ"],
        optionsEn: ["550 CE", "563 CE", "570 CE", "580 CE"],
        correctIndex: 2,
        explanationBn: "রাসূলুল্লাহ (ﷺ) ৫৭০ খ্রিস্টাব্দে, ১২ রবিউল আউয়ালে মক্কায় জন্মগ্রহণ করেন।",
        explanationEn: "Prophet Muhammad (ﷺ) was born in 570 CE on 12 Rabi al-Awwal in Makkah.",
        category: "seerah",
        difficulty: "easy",
    },
    {
        questionBn: "রাসূল (ﷺ)-এর পিতার নাম কী?",
        questionEn: "What was the name of Prophet Muhammad's (ﷺ) father?",
        optionsBn: ["আবু তালিব", "আব্দুল্লাহ", "আব্দুল মুত্তালিব", "উমর"],
        optionsEn: ["Abu Talib", "Abdullah", "Abdul Muttalib", "Umar"],
        correctIndex: 1,
        explanationBn: "রাসূল (ﷺ)-এর পিতার নাম আব্দুল্লাহ। তিনি রাসূলের (ﷺ) জন্মের আগেই মৃত্যুবরণ করেন।",
        explanationEn: "The Prophet's (ﷺ) father's name was Abdullah. He passed away before the Prophet's birth.",
        category: "seerah",
        difficulty: "easy",
    },
    {
        questionBn: "রাসূল (ﷺ) কত বছর বয়সে নবুওয়াত পান?",
        questionEn: "At what age did Prophet Muhammad (ﷺ) receive Prophethood?",
        optionsBn: ["৩৫ বছর", "৩৮ বছর", "৪০ বছর", "৪৫ বছর"],
        optionsEn: ["35 years", "38 years", "40 years", "45 years"],
        correctIndex: 2,
        explanationBn: "রাসূল (ﷺ) ৪০ বছর বয়সে হেরা গুহায় প্রথম ওহী লাভ করেন।",
        explanationEn: "Prophet Muhammad (ﷺ) received the first revelation at the age of 40 in the Cave of Hira.",
        category: "seerah",
        difficulty: "easy",
    },
    {
        questionBn: "রাসূল (ﷺ)-এর প্রথম স্ত্রীর নাম কী?",
        questionEn: "What was the name of the Prophet's (ﷺ) first wife?",
        optionsBn: ["আয়েশা (রা)", "খাদিজা (রা)", "হাফসা (রা)", "জায়নাব (রা)"],
        optionsEn: ["Aisha (RA)", "Khadijah (RA)", "Hafsa (RA)", "Zaynab (RA)"],
        correctIndex: 1,
        explanationBn: "হযরত খাদিজা (রা) ছিলেন রাসূলের (ﷺ) প্রথম স্ত্রী। তিনি প্রথম মুসলিমও ছিলেন।",
        explanationEn: "Khadijah (RA) was the first wife of the Prophet (ﷺ) and the first Muslim.",
        category: "seerah",
        difficulty: "easy",
    },
    {
        questionBn: "মদীনায় হিজরতের সময় রাসূল (ﷺ)-এর সঙ্গী কে ছিলেন?",
        questionEn: "Who accompanied the Prophet (ﷺ) during the migration (Hijra) to Madinah?",
        optionsBn: ["উমর (রা)", "আলী (রা)", "আবু বকর (রা)", "উসমান (রা)"],
        optionsEn: ["Umar (RA)", "Ali (RA)", "Abu Bakr (RA)", "Uthman (RA)"],
        correctIndex: 2,
        explanationBn: "হিজরতের সময় হযরত আবু বকর (রা) রাসূলের (ﷺ) সঙ্গী ছিলেন।",
        explanationEn: "Abu Bakr (RA) was the companion of the Prophet (ﷺ) during the Hijra to Madinah.",
        category: "seerah",
        difficulty: "easy",
    },
    {
        questionBn: "ইসলামের ইতিহাসে প্রথম যুদ্ধ কোনটি?",
        questionEn: "What was the first battle in Islamic history?",
        optionsBn: ["বদর", "উহুদ", "খন্দক", "হুনায়ন"],
        optionsEn: ["Badr", "Uhud", "Khandaq", "Hunayn"],
        correctIndex: 0,
        explanationBn: "৬২৪ খ্রিস্টাব্দে (২য় হিজরি) বদর যুদ্ধ সংঘটিত হয়। এটি ইসলামের প্রথম প্রধান যুদ্ধ।",
        explanationEn: "The Battle of Badr took place in 624 CE (2nd Hijri). It was the first major battle of Islam.",
        category: "seerah",
        difficulty: "normal",
    },
    {
        questionBn: "মক্কা বিজয় কোন হিজরি সনে হয়েছিল?",
        questionEn: "In which Hijri year did the Conquest of Makkah take place?",
        optionsBn: ["৬ষ্ঠ হিজরি", "৭ম হিজরি", "৮ম হিজরি", "৯ম হিজরি"],
        optionsEn: ["6th Hijri", "7th Hijri", "8th Hijri", "9th Hijri"],
        correctIndex: 2,
        explanationBn: "মক্কা বিজয় ৮ম হিজরির রমজান মাসে (৬৩০ খ্রিস্টাব্দ) সংঘটিত হয়েছিল।",
        explanationEn: "The Conquest of Makkah took place in Ramadan of the 8th Hijri year (630 CE).",
        category: "seerah",
        difficulty: "normal",
    },
    {
        questionBn: "বিদায় হজে রাসূল (ﷺ) কত সন খ্রিস্টাব্দে ভাষণ দিয়েছিলেন?",
        questionEn: "In which year CE did the Prophet (ﷺ) deliver the Farewell Sermon?",
        optionsBn: ["৬২৮ খ্রিস্টাব্দ", "৬৩০ খ্রিস্টাব্দ", "৬৩২ খ্রিস্টাব্দ", "৬৩৪ খ্রিস্টাব্দ"],
        optionsEn: ["628 CE", "630 CE", "632 CE", "634 CE"],
        correctIndex: 2,
        explanationBn: "রাসূল (ﷺ) ৬৩২ খ্রিস্টাব্দে আরাফাতের ময়দানে বিদায় হজের ঐতিহাসিক ভাষণ প্রদান করেন।",
        explanationEn: "The Prophet (ﷺ) delivered the Farewell Sermon at the Plain of Arafat in 632 CE.",
        category: "seerah",
        difficulty: "normal",
    },

    // ─── HADITH ───
    {
        questionBn: "'আমল নিয়্যাতের উপর নির্ভরশীল' — এই হাদিসটি কোন সাহাবী থেকে বর্ণিত?",
        questionEn: "'Actions are judged by intentions' — from which companion is this Hadith narrated?",
        optionsBn: ["আবু হুরায়রা (রা)", "উমর ইবনুল খাত্তাব (রা)", "আলী (রা)", "ইবনে মাসউদ (রা)"],
        optionsEn: ["Abu Hurairah (RA)", "Umar ibn Al-Khattab (RA)", "Ali (RA)", "Ibn Masud (RA)"],
        correctIndex: 1,
        explanationBn: "এই বিখ্যাত হাদিসটি হযরত উমর ইবনুল খাত্তাব (রা) থেকে বর্ণিত। (বুখারি ও মুসলিম)",
        explanationEn: "This famous Hadith is narrated from Umar ibn Al-Khattab (RA). (Bukhari & Muslim)",
        category: "hadith",
        difficulty: "normal",
    },
    {
        questionBn: "সহিহ বুখারিতে মোট কতটি হাদিস আছে?",
        questionEn: "How many Hadiths are in Sahih Bukhari (approximately)?",
        optionsBn: ["৫,০০০টি", "৭,২৭৫টি", "৯,০০০টি", "১২,০০০টি"],
        optionsEn: ["5,000", "7,275", "9,000", "12,000"],
        correctIndex: 1,
        explanationBn: "সহিহ বুখারিতে প্রায় ৭,২৭৫টি হাদিস আছে (পুনরাবৃত্তি বাদ দিয়ে)।",
        explanationEn: "Sahih Bukhari contains approximately 7,275 Hadiths (excluding repetitions).",
        category: "hadith",
        difficulty: "hard",
    },
    {
        questionBn: "কোন হাদিস গ্রন্থকে কুতুবুস সিত্তার মধ্যে সবচেয়ে বিশুদ্ধ মনে করা হয়?",
        questionEn: "Which Hadith book is considered the most authentic in the Kutub al-Sittah?",
        optionsBn: ["সহিহ মুসলিম", "সুনানু আবি দাউদ", "সহিহ বুখারি", "সুনানু তিরমিযী"],
        optionsEn: ["Sahih Muslim", "Sunan Abu Dawud", "Sahih Bukhari", "Sunan Tirmidhi"],
        correctIndex: 2,
        explanationBn: "সহিহ বুখারিকে কুরআনের পর সবচেয়ে বিশুদ্ধ গ্রন্থ হিসেবে বিবেচনা করা হয়।",
        explanationEn: "Sahih Bukhari is considered the most authentic book after the Quran.",
        category: "hadith",
        difficulty: "normal",
    },
    {
        questionBn: "ইমাম বুখারি (রহ)-এর পুরো নাম কী?",
        questionEn: "What is the full name of Imam Bukhari (RH)?",
        optionsBn: [
            "মুহাম্মাদ ইবনু ইসমাঈল আল-বুখারি",
            "আহমাদ ইবনু মুহাম্মাদ আল-বুখারি",
            "আব্দুল্লাহ ইবনু ইদরীস আল-বুখারি",
            "ইবরাহিম ইবনু আদহাম আল-বুখারি",
        ],
        optionsEn: [
            "Muhammad ibn Ismail al-Bukhari",
            "Ahmad ibn Muhammad al-Bukhari",
            "Abdullah ibn Idris al-Bukhari",
            "Ibrahim ibn Adham al-Bukhari",
        ],
        correctIndex: 0,
        explanationBn: "ইমাম বুখারির পুরো নাম হলো আবু আব্দুল্লাহ মুহাম্মাদ ইবনু ইসমাঈল ইবনু ইবরাহিম আল-বুখারি।",
        explanationEn: "Imam Bukhari's full name is Abu Abdullah Muhammad ibn Ismail ibn Ibrahim al-Bukhari.",
        category: "hadith",
        difficulty: "hard",
    },

    // ─── FIQH ───
    {
        questionBn: "ইসলামে প্রতিদিন কতটি ফরজ নামাজ আছে?",
        questionEn: "How many daily obligatory (Fardh) prayers are there in Islam?",
        optionsBn: ["৩টি", "৪টি", "৫টি", "৬টি"],
        optionsEn: ["3", "4", "5", "6"],
        correctIndex: 2,
        explanationBn: "ইসলামে প্রতিদিন ৫টি ফরজ নামাজ আছে: ফজর, যোহর, আসর, মাগরিব ও ইশা।",
        explanationEn: "There are 5 obligatory daily prayers in Islam: Fajr, Dhuhr, Asr, Maghrib, and Isha.",
        category: "fiqh",
        difficulty: "easy",
    },
    {
        questionBn: "রমজান মাসে রোজা রাখা ইসলামের কততম স্তম্ভ?",
        questionEn: "Fasting in Ramadan is which pillar of Islam?",
        optionsBn: ["দ্বিতীয়", "তৃতীয়", "চতুর্থ", "পঞ্চম"],
        optionsEn: ["Second", "Third", "Fourth", "Fifth"],
        correctIndex: 2,
        explanationBn: "রমজানের রোজা ইসলামের পাঁচটি স্তম্ভের মধ্যে চতুর্থ।",
        explanationEn: "Fasting in Ramadan is the fourth pillar of Islam.",
        category: "fiqh",
        difficulty: "easy",
    },
    {
        questionBn: "যাকাত ফরজ হওয়ার জন্য নিসাব কত (স্বর্ণের ক্ষেত্রে)?",
        questionEn: "What is the Nisab for Zakat in terms of gold?",
        optionsBn: ["৫ তোলা", "৭.৫ তোলা", "৮.৫ তোলা", "১০ তোলা"],
        optionsEn: ["5 Tola", "7.5 Tola", "8.5 Tola", "10 Tola"],
        correctIndex: 1,
        explanationBn: "স্বর্ণের ক্ষেত্রে নিসাব হলো ৭.৫ তোলা (প্রায় ৮৭.৪৮ গ্রাম)।",
        explanationEn: "The Nisab for gold is 7.5 Tola (approximately 87.48 grams).",
        category: "fiqh",
        difficulty: "normal",
    },
    {
        questionBn: "হজ ফরজ হওয়ার শর্ত কী?",
        questionEn: "What is the condition for Hajj being obligatory?",
        optionsBn: ["শুধু শারীরিক সক্ষমতা", "শুধু আর্থিক সক্ষমতা", "শারীরিক ও আর্থিক উভয় সক্ষমতা", "বয়স ৩০ বছর হওয়া"],
        optionsEn: ["Physical ability only", "Financial ability only", "Both physical and financial ability", "Being 30 years old"],
        correctIndex: 2,
        explanationBn: "হজ ফরজ হওয়ার জন্য শারীরিক ও আর্থিক উভয় সক্ষমতা থাকা শর্ত।",
        explanationEn: "Both physical and financial ability are conditions for Hajj to be obligatory.",
        category: "fiqh",
        difficulty: "normal",
    },
    {
        questionBn: "ফজরের নামাজে কত রাকাত সুন্নত?",
        questionEn: "How many Rakats of Sunnah are there in Fajr prayer?",
        optionsBn: ["২ রাকাত", "৩ রাকাত", "৪ রাকাত", "সুন্নত নেই"],
        optionsEn: ["2 Rakats", "3 Rakats", "4 Rakats", "No Sunnah"],
        correctIndex: 0,
        explanationBn: "ফজরের নামাজের আগে ২ রাকাত সুন্নত পড়তে হয়।",
        explanationEn: "There are 2 Rakats of Sunnah before the Fajr prayer.",
        category: "fiqh",
        difficulty: "easy",
    },
    {
        questionBn: "তায়াম্মুম কখন করা যায়?",
        questionEn: "When is Tayammum (dry ablution) permitted?",
        optionsBn: [
            "যখন ইচ্ছা",
            "শুধু সফরে",
            "পানি না পাওয়া গেলে বা পানি ব্যবহার ক্ষতিকারক হলে",
            "শুধু অসুস্থ অবস্থায়"
        ],
        optionsEn: [
            "Whenever desired",
            "Only while traveling",
            "When water is unavailable or harmful to use",
            "Only when sick"
        ],
        correctIndex: 2,
        explanationBn: "পানি না পাওয়া গেলে, বা পানি ব্যবহার শরীরের জন্য ক্ষতিকারক হলে তায়াম্মুম করার অনুমতি আছে।",
        explanationEn: "Tayammum is permitted when water is unavailable or using water would be harmful to the body.",
        category: "fiqh",
        difficulty: "normal",
    },
    {
        questionBn: "ঈদুল ফিতরের নামাজ কত রাকাত?",
        questionEn: "How many Rakats is the Eid al-Fitr prayer?",
        optionsBn: ["দুই রাকাত", "চার রাকাত", "ছয় রাকাত", "তিন রাকাত"],
        optionsEn: ["Two Rakats", "Four Rakats", "Six Rakats", "Three Rakats"],
        correctIndex: 0,
        explanationBn: "ঈদুল ফিতরের নামাজ ২ রাকাত (অতিরিক্ত তাকবির সহ)।",
        explanationEn: "Eid al-Fitr prayer is 2 Rakats (with additional takbeers).",
        category: "fiqh",
        difficulty: "easy",
    },

    // ─── GENERAL (Islamic History & Knowledge) ───
    {
        questionBn: "মসজিদুল হারাম কোন শহরে অবস্থিত?",
        questionEn: "In which city is Masjid al-Haram located?",
        optionsBn: ["মদীনা", "মক্কা", "জেরুজালেম", "তায়েফ"],
        optionsEn: ["Madinah", "Makkah", "Jerusalem", "Taif"],
        correctIndex: 1,
        explanationBn: "মসজিদুল হারাম সৌদি আরবের মক্কায় অবস্থিত। এটি বিশ্বের সবচেয়ে বড় মসজিদ।",
        explanationEn: "Masjid al-Haram is located in Makkah, Saudi Arabia. It is the largest mosque in the world.",
        category: "general",
        difficulty: "easy",
    },
    {
        questionBn: "কাবা শরীফ কোন আকৃতির?",
        questionEn: "What shape is the Kaaba?",
        optionsBn: ["গোলাকার", "ত্রিভুজাকার", "আয়তাকার", "পঞ্চভুজাকার"],
        optionsEn: ["Circular", "Triangular", "Rectangular/Cubic", "Pentagonal"],
        correctIndex: 2,
        explanationBn: "কাবা শরীফ একটি ঘনকাকৃতির (Cubic) পাথরের স্থাপনা।",
        explanationEn: "The Kaaba is a cubic stone structure.",
        category: "general",
        difficulty: "easy",
    },
    {
        questionBn: "ইসলামী ক্যালেন্ডারে রমজান কততম মাস?",
        questionEn: "Ramadan is which month in the Islamic (Hijri) calendar?",
        optionsBn: ["৭ম মাস", "৮ম মাস", "৯ম মাস", "১০ম মাস"],
        optionsEn: ["7th month", "8th month", "9th month", "10th month"],
        correctIndex: 2,
        explanationBn: "রমজান ইসলামী (হিজরি) ক্যালেন্ডারের ৯ম মাস।",
        explanationEn: "Ramadan is the 9th month of the Islamic (Hijri) calendar.",
        category: "general",
        difficulty: "easy",
    },
    {
        questionBn: "লাইলাতুল কদর কোন রাতে খোঁজা উচিত?",
        questionEn: "On which nights should Laylatul Qadr be sought?",
        optionsBn: ["রমজানের প্রথম ১০ রাতে", "রমজানের মধ্য ১০ রাতে", "রমজানের শেষ বিজোড় ১০ রাতে", "ঈদের রাতে"],
        optionsEn: ["First 10 nights of Ramadan", "Middle 10 nights of Ramadan", "Last odd nights of the last 10 of Ramadan", "The night of Eid"],
        correctIndex: 2,
        explanationBn: "রাসূল (ﷺ) বলেছেন, রমজানের শেষ ১০ দিনের বিজোড় রাতগুলোতে লাইলাতুল কদর খোঁজো। (বুখারি)",
        explanationEn: "The Prophet (ﷺ) said to seek Laylatul Qadr in the odd nights of the last 10 of Ramadan. (Bukhari)",
        category: "general",
        difficulty: "normal",
    },
    {
        questionBn: "পৃথিবীতে সর্বপ্রথম নির্মিত মসজিদ কোনটি?",
        questionEn: "Which is considered the first mosque built on Earth?",
        optionsBn: ["মসজিদুল হারাম", "মসজিদুল আকসা", "মসজিদে নববী", "মসজিদে কুবা"],
        optionsEn: ["Masjid al-Haram", "Masjid al-Aqsa", "Masjid an-Nabawi", "Masjid Quba"],
        correctIndex: 0,
        explanationBn: "মসজিদুল হারামকে (কাবা) পৃথিবীতে প্রথম নির্মিত মসজিদ হিসেবে গণ্য করা হয়।",
        explanationEn: "Masjid al-Haram (the Kaaba) is considered the first mosque built on Earth.",
        category: "general",
        difficulty: "normal",
    },
    {
        questionBn: "ইসলামে হিজরি সন গণনা কোন ঘটনা থেকে শুরু হয়?",
        questionEn: "From which event does the Hijri calendar start?",
        optionsBn: ["কুরআন নাজিলের বছর থেকে", "রাসূলের জন্ম বছর থেকে", "মদিনায় হিজরতের বছর থেকে", "মক্কা বিজয়ের বছর থেকে"],
        optionsEn: ["Year of Quran's revelation", "Year of Prophet's birth", "Year of Hijra to Madinah", "Year of Conquest of Makkah"],
        correctIndex: 2,
        explanationBn: "হিজরি সন মদিনায় হিজরতের বছর (৬২২ খ্রিস্টাব্দ) থেকে গণনা শুরু হয়।",
        explanationEn: "The Hijri calendar starts from the year of the migration (Hijra) to Madinah (622 CE).",
        category: "general",
        difficulty: "normal",
    },
    {
        questionBn: "মসজিদে নববী কোথায় অবস্থিত?",
        questionEn: "Where is Masjid an-Nabawi located?",
        optionsBn: ["মক্কা", "মদিনা", "জেদ্দা", "তায়েফ"],
        optionsEn: ["Makkah", "Madinah", "Jeddah", "Taif"],
        correctIndex: 1,
        explanationBn: "মসজিদে নববী সৌদি আরবের মদিনায় অবস্থিত। এটি রাসূল (ﷺ) নিজে নির্মাণ করেছিলেন।",
        explanationEn: "Masjid an-Nabawi is located in Madinah, Saudi Arabia. It was built by the Prophet (ﷺ) himself.",
        category: "general",
        difficulty: "easy",
    },

    // ─── BOSS LEVEL (hard difficulty) ───
    {
        questionBn: "কুরআনের কোন সূরায় মৌমাছির কথা উল্লেখ আছে?",
        questionEn: "Which Surah of the Quran mentions the bee?",
        optionsBn: ["সূরা আন-নাহল", "সূরা আল-আনআম", "সূরা আন-নামল", "সূরা আল-ফীল"],
        optionsEn: ["Surah An-Nahl", "Surah Al-An'am", "Surah An-Naml", "Surah Al-Fil"],
        correctIndex: 0,
        explanationBn: "সূরা আন-নাহল মানে 'মৌমাছি' এবং এই সূরায় আল্লাহ মৌমাছির কথা উল্লেখ করেছেন।",
        explanationEn: "Surah An-Nahl means 'The Bee' and Allah mentions the bee in this Surah.",
        category: "quran",
        difficulty: "boss",
    },
    {
        questionBn: "ইমাম আবু হানিফার (রহ) পুরো নাম কী?",
        questionEn: "What is the full name of Imam Abu Hanifa (RH)?",
        optionsBn: [
            "নু'মান ইবনু সাবিত",
            "মুহাম্মাদ ইবনু ইদরীস",
            "মালিক ইবনু আনাস",
            "আহমাদ ইবনু হাম্বাল"
        ],
        optionsEn: [
            "Nu'man ibn Thabit",
            "Muhammad ibn Idris",
            "Malik ibn Anas",
            "Ahmad ibn Hanbal"
        ],
        correctIndex: 0,
        explanationBn: "ইমাম আবু হানিফার পুরো নাম হলো আবু হানিফা নু'মান ইবনু সাবিত আল-কুফি।",
        explanationEn: "Imam Abu Hanifa's full name is Abu Hanifah Nu'man ibn Thabit al-Kufi.",
        category: "fiqh",
        difficulty: "boss",
    },
    {
        questionBn: "কুরআনে মোট কতটি আয়াত আছে?",
        questionEn: "How many verses (Ayahs) are in the Quran?",
        optionsBn: ["৬,২০০টি", "৬,২৩৬টি", "৬,৬৬৬টি", "৬,৫০০টি"],
        optionsEn: ["6,200", "6,236", "6,666", "6,500"],
        correctIndex: 1,
        explanationBn: "পবিত্র কুরআনে মোট ৬,২৩৬টি আয়াত রয়েছে।",
        explanationEn: "The Holy Quran contains a total of 6,236 verses.",
        category: "quran",
        difficulty: "boss",
    },
    {
        questionBn: "কোন সাহাবীকে 'সাইফুল্লাহ' (আল্লাহর তলোয়ার) উপাধি দেওয়া হয়েছিল?",
        questionEn: "Which companion was given the title 'Sayfullah' (Sword of Allah)?",
        optionsBn: ["হযরত আলী (রা)", "হযরত উমর (রা)", "হযরত খালিদ ইবন ওয়ালিদ (রা)", "হযরত আবু উবায়দা (রা)"],
        optionsEn: ["Ali (RA)", "Umar (RA)", "Khalid ibn al-Walid (RA)", "Abu Ubayda (RA)"],
        correctIndex: 2,
        explanationBn: "রাসূলুল্লাহ (ﷺ) হযরত খালিদ ইবনুল ওয়ালিদ (রা)-কে 'সাইফুল্লাহ' উপাধি দিয়েছিলেন।",
        explanationEn: "The Prophet (ﷺ) gave Khalid ibn al-Walid (RA) the title 'Sayfullah' (Sword of Allah).",
        category: "seerah",
        difficulty: "boss",
    },
    {
        questionBn: "গারে হেরায় প্রথম ওহী নাজিলের সময় রাসূল (ﷺ)-এর বয়স ছিল কত?",
        questionEn: "How old was the Prophet (ﷺ) when the first revelation came in the Cave of Hira?",
        optionsBn: ["৩৮ বছর", "৪০ বছর", "৪২ বছর", "৪৫ বছর"],
        optionsEn: ["38 years", "40 years", "42 years", "45 years"],
        correctIndex: 1,
        explanationBn: "৬১০ খ্রিস্টাব্দে, ৪০ বছর বয়সে গারে হেরায় প্রথম ওহী নাজিল হয়।",
        explanationEn: "In 610 CE, at the age of 40, the first revelation came to the Cave of Hira.",
        category: "seerah",
        difficulty: "boss",
    },
    {
        questionBn: "কুরআনের কোন সূরাটি 'উম্মুল কিতাব' নামে পরিচিত?",
        questionEn: "Which Surah of the Quran is known as 'Ummul Kitab' (Mother of the Book)?",
        optionsBn: ["সূরা ইয়াসীন", "সূরা আল-বাকারা", "সূরা আল-ফাতিহা", "সূরা আল-ইখলাস"],
        optionsEn: ["Surah Ya-Sin", "Surah Al-Baqarah", "Surah Al-Fatihah", "Surah Al-Ikhlas"],
        correctIndex: 2,
        explanationBn: "সূরা আল-ফাতিহা 'উম্মুল কিতাব' বা 'কিতাবের মা' নামে পরিচিত। প্রতিটি নামাজে এটি পড়া ফরজ।",
        explanationEn: "Surah Al-Fatihah is known as 'Ummul Kitab'. It is obligatory in every prayer.",
        category: "quran",
        difficulty: "boss",
    },
    {
        questionBn: "কুতুবুস সিত্তা মানে কী?",
        questionEn: "What does 'Kutub al-Sittah' mean?",
        optionsBn: ["চারটি মাযহাব", "ছয়টি বিশুদ্ধ হাদিস গ্রন্থ", "চারটি বিশুদ্ধ হাদিস গ্রন্থ", "ইসলামের পাঁচটি স্তম্ভ"],
        optionsEn: ["Four Madhabs", "Six authentic Hadith books", "Four authentic Hadith books", "Five Pillars of Islam"],
        correctIndex: 1,
        explanationBn: "কুতুবুস সিত্তা মানে 'ছয়টি বিশুদ্ধ হাদিস গ্রন্থ': বুখারি, মুসলিম, আবু দাউদ, তিরমিযী, নাসায়ী, ও ইবনে মাজাহ।",
        explanationEn: "Kutub al-Sittah means 'Six Authentic Hadith Books': Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasa'i, and Ibn Majah.",
        category: "hadith",
        difficulty: "boss",
    },
    {
        questionBn: "হযরত মূসা (আ)-কে কোন পর্বতে আল্লাহ সরাসরি কথা বলেছিলেন?",
        questionEn: "On which mountain did Allah speak directly to Prophet Musa (AS)?",
        optionsBn: ["জাবালে নূর", "জাবালে সাওর", "তূর পর্বত", "জাবালে রহমত"],
        optionsEn: ["Jabal an-Nur", "Jabal Thawr", "Mount Sinai (Tur)", "Jabal ar-Rahmah"],
        correctIndex: 2,
        explanationBn: "আল্লাহ তা'আলা তূর পর্বতে (মাউন্ট সিনাই) হযরত মূসা (আ)-এর সাথে সরাসরি কথা বলেছিলেন।",
        explanationEn: "Allah spoke directly to Prophet Musa (AS) on Mount Sinai (Jabal at-Tur).",
        category: "general",
        difficulty: "boss",
    },
    {
        questionBn: "হাজরে আসওয়াদ (কালো পাথর) কোথায় অবস্থিত?",
        questionEn: "Where is the Hajar al-Aswad (Black Stone) located?",
        optionsBn: ["কাবার পূর্ব কোণে", "কাবার পশ্চিম কোণে", "মসজিদের মেঝেতে", "সাফা পাহাড়ে"],
        optionsEn: ["Eastern corner of the Kaaba", "Western corner of the Kaaba", "On the mosque floor", "On Safa hill"],
        correctIndex: 0,
        explanationBn: "হাজরে আসওয়াদ কাবার পূর্ব-দক্ষিণ কোণে অবস্থিত। তাওয়াফ এখান থেকে শুরু হয়।",
        explanationEn: "The Hajar al-Aswad is located in the eastern corner of the Kaaba. Tawaf begins from here.",
        category: "general",
        difficulty: "boss",
    },
    {
        questionBn: "কোন নবীকে 'উলুল আযম' নবীদের একজন হিসেবে গণ্য করা হয়?",
        questionEn: "Which of the following is one of the five 'Ulul Azm' (Mighty Resolve) Prophets?",
        optionsBn: ["হযরত ইউসুফ (আ)", "হযরত দাউদ (আ)", "হযরত নূহ (আ)", "হযরত সুলাইমান (আ)"],
        optionsEn: ["Prophet Yusuf (AS)", "Prophet Dawud (AS)", "Prophet Nuh (AS)", "Prophet Sulayman (AS)"],
        correctIndex: 2,
        explanationBn: "উলুল আযম নবীরা হলেন: মুহাম্মাদ (ﷺ), ইবরাহিম (আ), মূসা (আ), ঈসা (আ), এবং নূহ (আ)।",
        explanationEn: "The five Ulul Azm Prophets are: Muhammad (ﷺ), Ibrahim (AS), Musa (AS), Isa (AS), and Nuh (AS).",
        category: "general",
        difficulty: "boss",
    },
];

async function main() {
    console.log('🌱 Seeding quiz questions...');

    // Clear existing questions first
    await prisma.quizQuestion.deleteMany({});
    console.log('🗑️  Cleared existing questions.');

    const created = await prisma.quizQuestion.createMany({
        data: questions.map(q => ({
            questionBn: q.questionBn,
            questionEn: q.questionEn,
            optionsBn: q.optionsBn,
            optionsEn: q.optionsEn,
            correctIndex: q.correctIndex,
            explanationBn: q.explanationBn || null,
            explanationEn: q.explanationEn || null,
            category: q.category,
            difficulty: q.difficulty,
            isActive: true,
        })),
    });

    console.log(`✅ Seeded ${created.count} quiz questions successfully!`);
    console.log(`📊 Breakdown:`);
    const categories = ['quran', 'seerah', 'hadith', 'fiqh', 'general'];
    for (const cat of categories) {
        const count = questions.filter(q => q.category === cat).length;
        console.log(`   - ${cat}: ${count} questions`);
    }
    const bossCount = questions.filter(q => q.difficulty === 'boss').length;
    console.log(`   - boss difficulty: ${bossCount} questions`);
}

main()
    .catch(e => { console.error('❌ Seed failed:', e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
