import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
    // ─── QURAN (10 questions) ───────────────────────────────────────────────
    {
        questionBn: 'কুরআনের কোন সূরাটিকে "কুরআনের হৃদয়" বলা হয়?',
        questionEn: 'Which Surah of the Quran is called the "Heart of the Quran"?',
        optionsBn: ['সূরা আল-ফাতিহা', 'সূরা ইয়াসিন', 'সূরা আল-বাকারা', 'সূরা আর-রহমান'],
        optionsEn: ['Surah Al-Fatiha', 'Surah Yasin', 'Surah Al-Baqarah', 'Surah Ar-Rahman'],
        correctIndex: 1,
        explanationBn: 'সূরা ইয়াসিন (৩৬তম সূরা) কে নবী (ﷺ) "কুরআনের হৃদয়" বলেছেন।',
        explanationEn: 'Surah Yasin (36th chapter) is called the "Heart of the Quran" by the Prophet (ﷺ).',
        category: 'quran', difficulty: 'easy',
    },
    {
        questionBn: 'পবিত্র কুরআনে মোট কতটি সূরা আছে?',
        questionEn: 'How many Surahs are there in the Holy Quran?',
        optionsBn: ['১১০', '১১২', '১১৪', '১১৬'],
        optionsEn: ['110', '112', '114', '116'],
        correctIndex: 2,
        explanationBn: 'পবিত্র কুরআনে মোট ১১৪টি সূরা আছে।',
        explanationEn: 'The Holy Quran contains 114 Surahs in total.',
        category: 'quran', difficulty: 'easy',
    },
    {
        questionBn: 'কুরআনের দীর্ঘতম সূরা কোনটি?',
        questionEn: 'Which is the longest Surah in the Quran?',
        optionsBn: ['সূরা আলে-ইমরান', 'সূরা আল-বাকারা', 'সূরা আন-নিসা', 'সূরা আল-মায়িদা'],
        optionsEn: ['Surah Ale-Imran', 'Surah Al-Baqarah', 'Surah An-Nisa', 'Surah Al-Maidah'],
        correctIndex: 1,
        explanationBn: 'সূরা আল-বাকারা কুরআনের দীর্ঘতম সূরা, যাতে ২৮৬টি আয়াত রয়েছে।',
        explanationEn: 'Surah Al-Baqarah is the longest Surah with 286 verses.',
        category: 'quran', difficulty: 'easy',
    },
    {
        questionBn: 'কুরআনের ক্ষুদ্রতম সূরা কোনটি?',
        questionEn: 'Which is the shortest Surah in the Quran?',
        optionsBn: ['সূরা আল-ইখলাস', 'সূরা আল-ফালাক', 'সূরা আল-কাউসার', 'সূরা আন-নাস'],
        optionsEn: ['Surah Al-Ikhlas', 'Surah Al-Falaq', 'Surah Al-Kawthar', 'Surah An-Nas'],
        correctIndex: 2,
        explanationBn: 'সূরা আল-কাউসার কুরআনের ক্ষুদ্রতম সূরা, যাতে মাত্র ৩টি আয়াত আছে।',
        explanationEn: 'Surah Al-Kawthar is the shortest Surah with only 3 verses.',
        category: 'quran', difficulty: 'easy',
    },
    {
        questionBn: '"আয়াতুল কুরসি" কুরআনের কোন সূরায় আছে?',
        questionEn: 'In which Surah is "Ayatul Kursi" located?',
        optionsBn: ['সূরা আলে-ইমরান', 'সূরা আল-বাকারা', 'সূরা আল-হাশর', 'সূরা আন-নূর'],
        optionsEn: ['Surah Ale-Imran', 'Surah Al-Baqarah', 'Surah Al-Hashr', 'Surah An-Nur'],
        correctIndex: 1,
        explanationBn: 'আয়াতুল কুরসি সূরা আল-বাকারার ২৫৫ নম্বর আয়াত।',
        explanationEn: 'Ayatul Kursi is verse 255 of Surah Al-Baqarah.',
        category: 'quran', difficulty: 'normal',
    },
    {
        questionBn: 'কুরআনের কোন সূরায় "বিসমিল্লাহ" দুইবার আছে?',
        questionEn: 'In which Surah does "Bismillah" appear twice?',
        optionsBn: ['সূরা আল-ফাতিহা', 'সূরা আন-নামল', 'সূরা আল-বাকারা', 'সূরা আল-আনফাল'],
        optionsEn: ['Surah Al-Fatiha', 'Surah An-Naml', 'Surah Al-Baqarah', 'Surah Al-Anfal'],
        correctIndex: 1,
        explanationBn: 'সূরা আন-নামলে (২৭:৩০) নবী সুলাইমান (আ) এর চিঠির শুরুতে বিসমিল্লাহ আসে, তাই এই সূরায় দুইটি বিসমিল্লাহ আছে।',
        explanationEn: 'Surah An-Naml contains "Bismillah" twice — once at the start and once in verse 30 (the letter of Prophet Sulaiman).',
        category: 'quran', difficulty: 'hard',
    },
    {
        questionBn: 'কুরআনে মোট কতটি পারা (জুয) আছে?',
        questionEn: 'How many Juz (Paras) are there in the Quran?',
        optionsBn: ['২৫', '২৮', '৩০', '৩২'],
        optionsEn: ['25', '28', '30', '32'],
        correctIndex: 2,
        explanationBn: 'পবিত্র কুরআন ৩০টি পারায় (জুয) বিভক্ত।',
        explanationEn: 'The Holy Quran is divided into 30 Juz (Paras).',
        category: 'quran', difficulty: 'easy',
    },
    {
        questionBn: 'কুরআনের কোন আয়াতটি সবচেয়ে বড়?',
        questionEn: 'Which verse of the Quran is the longest?',
        optionsBn: ['আল-বাকারা ২৫৫', 'আল-বাকারা ২৮২', 'আলে-ইমরান ১৮', 'আন-নিসা ১১'],
        optionsEn: ['Al-Baqarah 255', 'Al-Baqarah 282', 'Ale-Imran 18', 'An-Nisa 11'],
        correctIndex: 1,
        explanationBn: 'সূরা আল-বাকারার ২৮২ নম্বর আয়াত কুরআনের দীর্ঘতম আয়াত — ঋণ লেনদেনের নিয়ম সম্পর্কে।',
        explanationEn: 'Al-Baqarah verse 282 is the longest verse, dealing with the rules of debt transactions.',
        category: 'quran', difficulty: 'hard',
    },
    {
        questionBn: 'কুরআনে কতজন নবীর নাম উল্লেখ আছে?',
        questionEn: 'How many Prophets are mentioned by name in the Quran?',
        optionsBn: ['২০', '২৩', '২৫', '২৮'],
        optionsEn: ['20', '23', '25', '28'],
        correctIndex: 2,
        explanationBn: 'কুরআনে ২৫ জন নবীর নাম সরাসরি উল্লেখ আছে।',
        explanationEn: '25 Prophets are mentioned by name in the Quran.',
        category: 'quran', difficulty: 'normal',
    },
    {
        questionBn: 'কুরআনে সবচেয়ে বেশিবার কোন নবীর নাম এসেছে?',
        questionEn: 'Which Prophet\'s name appears most frequently in the Quran?',
        optionsBn: ['মুহাম্মদ (ﷺ)', 'মুসা (আ)', 'ইব্রাহিম (আ)', 'ঈসা (আ)'],
        optionsEn: ['Muhammad (ﷺ)', 'Musa (AS)', 'Ibrahim (AS)', 'Isa (AS)'],
        correctIndex: 1,
        explanationBn: 'নবী মুসা (আ) এর নাম কুরআনে সবচেয়ে বেশি — ১৩৬ বার উল্লেখ আছে।',
        explanationEn: 'Prophet Musa (AS) is mentioned the most — 136 times in the Quran.',
        category: 'quran', difficulty: 'boss',
    },

    // ─── SEERAH (10 questions) ─────────────────────────────────────────────
    {
        questionBn: 'নবী মুহাম্মদ (ﷺ) কোন বছর জন্মগ্রহণ করেন?',
        questionEn: 'In which year was Prophet Muhammad (ﷺ) born?',
        optionsBn: ['৫৫০ খ্রিস্টাব্দ', '৫৭০ খ্রিস্টাব্দ', '৫৮০ খ্রিস্টাব্দ', '৫৯০ খ্রিস্টাব্দ'],
        optionsEn: ['550 CE', '570 CE', '580 CE', '590 CE'],
        correctIndex: 1,
        explanationBn: 'নবী (ﷺ) ৫৭০ খ্রিস্টাব্দে হস্তী বছরে মক্কায় জন্মগ্রহণ করেন।',
        explanationEn: 'The Prophet (ﷺ) was born in 570 CE, the Year of the Elephant, in Makkah.',
        category: 'seerah', difficulty: 'easy',
    },
    {
        questionBn: 'নবী (ﷺ) এর মায়ের নাম কী?',
        questionEn: 'What was the name of the Prophet\'s (ﷺ) mother?',
        optionsBn: ['খাদিজা', 'আমিনা', 'ফাতিমা', 'সুমাইয়া'],
        optionsEn: ['Khadijah', 'Aminah', 'Fatimah', 'Sumayyah'],
        correctIndex: 1,
        explanationBn: 'নবী (ﷺ) এর মায়ের নাম ছিল আমিনা বিনতে ওয়াহব।',
        explanationEn: 'The Prophet\'s (ﷺ) mother was Aminah bint Wahb.',
        category: 'seerah', difficulty: 'easy',
    },
    {
        questionBn: 'নবী (ﷺ) কত বছর বয়সে প্রথম ওহী লাভ করেন?',
        questionEn: 'At what age did the Prophet (ﷺ) receive the first revelation?',
        optionsBn: ['৩৫', '৩৮', '৪০', '৪৫'],
        optionsEn: ['35', '38', '40', '45'],
        correctIndex: 2,
        explanationBn: 'নবী (ﷺ) ৪০ বছর বয়সে হেরা গুহায় প্রথম ওহী পান।',
        explanationEn: 'The Prophet (ﷺ) received the first revelation in the Cave of Hira at the age of 40.',
        category: 'seerah', difficulty: 'easy',
    },
    {
        questionBn: 'হিজরত কোন বছর সংঘটিত হয়?',
        questionEn: 'In which year did the Hijra (migration to Madinah) take place?',
        optionsBn: ['৬১০ খ্রিস্টাব্দ', '৬১৫ খ্রিস্টাব্দ', '৬২২ খ্রিস্টাব্দ', '৬৩০ খ্রিস্টাব্দ'],
        optionsEn: ['610 CE', '615 CE', '622 CE', '630 CE'],
        correctIndex: 2,
        explanationBn: 'হিজরত ৬২২ খ্রিস্টাব্দে সংঘটিত হয়, যা ইসলামিক ক্যালেন্ডারের সূচনাবিন্দু।',
        explanationEn: 'The Hijra took place in 622 CE, marking the start of the Islamic calendar.',
        category: 'seerah', difficulty: 'normal',
    },
    {
        questionBn: 'মক্কা বিজয় কোন হিজরি সালে হয়?',
        questionEn: 'In which Hijri year did the Conquest of Makkah take place?',
        optionsBn: ['৬ হিজরি', '৭ হিজরি', '৮ হিজরি', '৯ হিজরি'],
        optionsEn: ['6 AH', '7 AH', '8 AH', '9 AH'],
        correctIndex: 2,
        explanationBn: 'মক্কা বিজয় ৮ হিজরিতে রমজান মাসে হয়।',
        explanationEn: 'The Conquest of Makkah took place in 8 AH during the month of Ramadan.',
        category: 'seerah', difficulty: 'normal',
    },
    {
        questionBn: 'নবী (ﷺ) এর প্রথম স্ত্রীর নাম কী?',
        questionEn: 'What was the name of the Prophet\'s (ﷺ) first wife?',
        optionsBn: ['আয়িশা (রা)', 'খাদিজা (রা)', 'হাফসা (রা)', 'জয়নব (রা)'],
        optionsEn: ['Aisha (RA)', 'Khadijah (RA)', 'Hafsa (RA)', 'Zaynab (RA)'],
        correctIndex: 1,
        explanationBn: 'হযরত খাদিজা (রা) নবী (ﷺ) এর প্রথম স্ত্রী ছিলেন।',
        explanationEn: 'Khadijah (RA) was the first wife of the Prophet (ﷺ).',
        category: 'seerah', difficulty: 'easy',
    },
    {
        questionBn: 'ইসলামের ইতিহাসে প্রথম শহীদ কে?',
        questionEn: 'Who was the first martyr (Shaheed) in Islamic history?',
        optionsBn: ['সুমাইয়া (রা)', 'বিলাল (রা)', 'আম্মার (রা)', 'খাব্বাব (রা)'],
        optionsEn: ['Sumayyah (RA)', 'Bilal (RA)', 'Ammar (RA)', 'Khabbab (RA)'],
        correctIndex: 0,
        explanationBn: 'সুমাইয়া বিনতে খায়্যাত (রা) ইসলামের প্রথম শহীদ, যাকে আবু জাহেল হত্যা করেছিল।',
        explanationEn: 'Sumayyah bint Khayyat (RA) was the first martyr of Islam, killed by Abu Jahl.',
        category: 'seerah', difficulty: 'normal',
    },
    {
        questionBn: 'বদরের যুদ্ধ কত হিজরিতে হয়?',
        questionEn: 'In which Hijri year did the Battle of Badr take place?',
        optionsBn: ['১ হিজরি', '২ হিজরি', '৩ হিজরি', '৪ হিজরি'],
        optionsEn: ['1 AH', '2 AH', '3 AH', '4 AH'],
        correctIndex: 1,
        explanationBn: 'বদরের যুদ্ধ ২ হিজরির ১৭ই রমজান সংঘটিত হয়।',
        explanationEn: 'The Battle of Badr took place on 17 Ramadan, 2 AH.',
        category: 'seerah', difficulty: 'normal',
    },
    {
        questionBn: 'নবী (ﷺ) কত বছর বয়সে ইন্তেকাল করেন?',
        questionEn: 'At what age did Prophet Muhammad (ﷺ) pass away?',
        optionsBn: ['৫৮', '৬০', '৬৩', '৬৫'],
        optionsEn: ['58', '60', '63', '65'],
        correctIndex: 2,
        explanationBn: 'নবী (ﷺ) ৬৩ বছর বয়সে ১১ হিজরির ১২ই রবিউল আউয়াল ইন্তেকাল করেন।',
        explanationEn: 'The Prophet (ﷺ) passed away at the age of 63 on 12 Rabi al-Awwal, 11 AH.',
        category: 'seerah', difficulty: 'normal',
    },
    {
        questionBn: 'মিরাজের রাতে নবী (ﷺ) কে কোন নবীর সাথে সাক্ষাৎ হয় ৬ষ্ঠ আসমানে?',
        questionEn: 'Which Prophet did the Prophet (ﷺ) meet in the 6th Heaven during Miraj?',
        optionsBn: ['ইদ্রিস (আ)', 'মুসা (আ)', 'ইব্রাহিম (আ)', 'হারুন (আ)'],
        optionsEn: ['Idris (AS)', 'Musa (AS)', 'Ibrahim (AS)', 'Harun (AS)'],
        correctIndex: 0,
        explanationBn: 'মিরাজের রাতে ৬ষ্ঠ আসমানে নবী (ﷺ) নবী ইদ্রিস (আ) এর সাথে সাক্ষাৎ করেন।',
        explanationEn: 'On the night of Miraj, the Prophet (ﷺ) met Prophet Idris (AS) in the 6th Heaven.',
        category: 'seerah', difficulty: 'boss',
    },

    // ─── HADITH (10 questions) ─────────────────────────────────────────────
    {
        questionBn: '"আমল নির্ভর করে নিয়তের উপর" — এটি কোন হাদিস গ্রন্থে আছে?',
        questionEn: '"Actions are judged by intentions" — In which Hadith collection is this?',
        optionsBn: ['সহিহ মুসলিম', 'সুনান তিরমিযি', 'সহিহ বুখারি', 'সুনান আবু দাউদ'],
        optionsEn: ['Sahih Muslim', 'Sunan Tirmidhi', 'Sahih Bukhari', 'Sunan Abu Dawud'],
        correctIndex: 2,
        explanationBn: 'এই বিখ্যাত হাদিসটি সহিহ বুখারির প্রথম হাদিস।',
        explanationEn: 'This famous hadith is the first hadith in Sahih Bukhari.',
        category: 'hadith', difficulty: 'normal',
    },
    {
        questionBn: 'হাদিস সংকলনে "সহিহ বুখারি" কততম শতাব্দীতে সংকলিত হয়?',
        questionEn: 'In which century was Sahih Bukhari compiled?',
        optionsBn: ['২য় হিজরি', '৩য় হিজরি', '৪র্থ হিজরি', '৫ম হিজরি'],
        optionsEn: ['2nd Hijri', '3rd Hijri', '4th Hijri', '5th Hijri'],
        correctIndex: 1,
        explanationBn: 'ইমাম বুখারি (রহ) ৩য় হিজরি শতাব্দীতে (মৃত্যু ২৫৬ হিজরি) সহিহ বুখারি সংকলন করেন।',
        explanationEn: 'Imam Bukhari (RH) compiled Sahih Bukhari in the 3rd Hijri century (died 256 AH).',
        category: 'hadith', difficulty: 'hard',
    },
    {
        questionBn: 'ইসলামের পাঁচটি স্তম্ভ কোন হাদিসে বর্ণিত হয়েছে?',
        questionEn: 'The five pillars of Islam are described in which famous Hadith?',
        optionsBn: ['হাদিসে জিবরাইল', 'হাদিসে মুয়াবিয়া', 'হাদিসে ইবনে উমর', 'হাদিসে আবু হুরায়রা'],
        optionsEn: ['Hadith of Jibril', 'Hadith of Muawiyah', 'Hadith of Ibn Umar', 'Hadith of Abu Hurairah'],
        correctIndex: 2,
        explanationBn: 'ইবনে উমর (রা) বর্ণিত হাদিসে ইসলামের পাঁচটি স্তম্ভ উল্লেখ আছে (বুখারি ও মুসলিম)।',
        explanationEn: 'The five pillars of Islam are mentioned in the Hadith narrated by Ibn Umar (RA) in Bukhari and Muslim.',
        category: 'hadith', difficulty: 'normal',
    },
    {
        questionBn: '"প্রতিবেশী সম্পর্কে জিবরাইল এত বেশি উপদেশ দিলেন যে আমি মনে করলাম তাকে উত্তরাধিকারী করা হবে" — কার বক্তব্য?',
        questionEn: '"Jibril kept advising me about neighbors so much I thought they would inherit" — whose statement?',
        optionsBn: ['উমর (রা)', 'আয়িশা (রা)', 'মুহাম্মদ (ﷺ)', 'আলি (রা)'],
        optionsEn: ['Umar (RA)', 'Aisha (RA)', 'Muhammad (ﷺ)', 'Ali (RA)'],
        correctIndex: 2,
        explanationBn: 'এটি নবী মুহাম্মদ (ﷺ) এর বক্তব্য, হাদিসটি বুখারি ও মুসলিমে আছে।',
        explanationEn: 'This is a statement of Prophet Muhammad (ﷺ), narrated in Bukhari and Muslim.',
        category: 'hadith', difficulty: 'hard',
    },
    {
        questionBn: 'হাদিসের কোন শাস্ত্রে বর্ণনাকারীদের জীবনী আলোচনা করা হয়?',
        questionEn: 'Which branch of Hadith science deals with the biographies of narrators?',
        optionsBn: ['উসুলুল হাদিস', 'ইলমুর রিজাল', 'ইলমুল মুসতালাহ', 'ইলমুল জারহ'],
        optionsEn: ['Usul al-Hadith', 'Ilm al-Rijal', 'Ilm al-Mustalahat', 'Ilm al-Jarh'],
        correctIndex: 1,
        explanationBn: '"ইলমুর রিজাল" হল হাদিসের সেই শাস্ত্র যেখানে বর্ণনাকারীদের নির্ভরযোগ্যতা যাচাই করা হয়।',
        explanationEn: '"Ilm al-Rijal" is the science of evaluating the reliability of Hadith narrators.',
        category: 'hadith', difficulty: 'boss',
    },
    {
        questionBn: 'কুতুবে সিত্তা কী?',
        questionEn: 'What is Kutub al-Sittah?',
        optionsBn: ['৬টি বিখ্যাত হাদিস গ্রন্থ', '৬জন বিখ্যাত সাহাবি', '৬টি ইসলামি আইন', '৬টি কুরআনের তাফসির'],
        optionsEn: ['6 major Hadith collections', '6 famous Companions', '6 Islamic laws', '6 Quran commentaries'],
        correctIndex: 0,
        explanationBn: 'কুতুবে সিত্তা হল ৬টি বিখ্যাত সহিহ হাদিস গ্রন্থ — বুখারি, মুসলিম, তিরমিযি, আবু দাউদ, নাসাঈ ও ইবনে মাজাহ।',
        explanationEn: 'Kutub al-Sittah refers to the six major Hadith collections — Bukhari, Muslim, Tirmidhi, Abu Dawud, Nasai, and Ibn Majah.',
        category: 'hadith', difficulty: 'normal',
    },
    {
        questionBn: '"মুসাফাহা করলে গুনাহ ঝরে পড়ে" — এটি কোন ধরনের হাদিস?',
        questionEn: 'A Hadith narrated by a single chain from each generation is called?',
        optionsBn: ['মুতাওয়াতির', 'আহাদ', 'হাসান', 'জঈফ'],
        optionsEn: ['Mutawatir', 'Ahad', 'Hasan', 'Daeef'],
        correctIndex: 1,
        explanationBn: 'একক সনদে বর্ণিত হাদিসকে "আহাদ" বলে। কখনও বর্ণনাকারী সংখ্যাভেদে আরও শ্রেণিবদ্ধ হয়।',
        explanationEn: 'A Hadith narrated by a single chain per generation is called "Ahad" Hadith.',
        category: 'hadith', difficulty: 'boss',
    },
    {
        questionBn: 'নবী (ﷺ) বলেছেন — "পরিষ্কার-পরিচ্ছন্নতা ঈমানের অর্ধেক।" এটি কোন কিতাবে?',
        questionEn: '"Cleanliness is half of faith" — In which book is this Hadith?',
        optionsBn: ['বুখারি', 'আবু দাউদ', 'মুসলিম', 'তিরমিযি'],
        optionsEn: ['Bukhari', 'Abu Dawud', 'Muslim', 'Tirmidhi'],
        correctIndex: 2,
        explanationBn: '"আত-তাহুরু শাতরুল ঈমান" হাদিসটি সহিহ মুসলিমে বর্ণিত।',
        explanationEn: '"Al-Tahuuru shatur al-iman" is narrated in Sahih Muslim.',
        category: 'hadith', difficulty: 'normal',
    },
    {
        questionBn: '"যে ব্যক্তি আল্লাহ ও আখিরাতে বিশ্বাস করে, সে যেন মেহমানকে সম্মান করে।" — এটা কার হাদিস?',
        questionEn: '"Whoever believes in Allah and the Last Day, let him honor his guest." — Whose narration?',
        optionsBn: ['আনাস (রা)', 'আবু হুরায়রা (রা)', 'উমর (রা)', 'আবু যার (রা)'],
        optionsEn: ['Anas (RA)', 'Abu Hurairah (RA)', 'Umar (RA)', 'Abu Dharr (RA)'],
        correctIndex: 1,
        explanationBn: 'এটি আবু হুরায়রা (রা) বর্ণিত হাদিস, সহিহ বুখারি ও মুসলিমে আছে।',
        explanationEn: 'This is narrated by Abu Hurairah (RA) in Sahih Bukhari and Muslim.',
        category: 'hadith', difficulty: 'normal',
    },
    {
        questionBn: 'হাদিসে কুদসি এবং সাধারণ হাদিসের পার্থক্য কী?',
        questionEn: 'What is the difference between Hadith Qudsi and regular Hadith?',
        optionsBn: ['হাদিসে কুদসি কুরআনের অংশ', 'এতে আল্লাহ প্রথম পুরুষে কথা বলেন', 'এটা শুধু মক্কায় বলা হয়েছে', 'এটা শুধু ফরজ বিষয়ে'],
        optionsEn: ['Hadith Qudsi is part of Quran', 'Allah speaks in first person in it', 'It was only said in Makkah', 'It only covers obligatory acts'],
        correctIndex: 1,
        explanationBn: 'হাদিসে কুদসিতে আল্লাহ তাআলা সরাসরি প্রথম পুরুষে কথা বলেন, কিন্তু এটি কুরআনের অংশ নয়।',
        explanationEn: 'In Hadith Qudsi, Allah speaks in the first person, but it is not part of the Quran.',
        category: 'hadith', difficulty: 'boss',
    },

    // ─── FIQH (10 questions) ───────────────────────────────────────────────
    {
        questionBn: 'ফজরের ফরজ নামাজ কত রাকাত?',
        questionEn: 'How many Rakat are in the Fard (obligatory) Fajr prayer?',
        optionsBn: ['১', '২', '৩', '৪'],
        optionsEn: ['1', '2', '3', '4'],
        correctIndex: 1,
        explanationBn: 'ফজরের ফরজ নামাজ ২ রাকাত।',
        explanationEn: 'The obligatory Fajr prayer consists of 2 Rakat.',
        category: 'fiqh', difficulty: 'easy',
    },
    {
        questionBn: 'রমজানে রোজা রাখা কার উপর ফরজ?',
        questionEn: 'Fasting in Ramadan is obligatory (Fard) upon whom?',
        optionsBn: ['সকল মুসলিমের উপর', 'শুধু প্রাপ্তবয়স্ক মুসলিমের উপর', 'শুধু পুরুষের উপর', 'শুধু সুস্থ মুসলিমের উপর'],
        optionsEn: ['All Muslims', 'Adult Muslims only', 'Men only', 'Healthy Muslims only'],
        correctIndex: 1,
        explanationBn: 'রোজা প্রাপ্তবয়স্ক, সুস্থ, মুকিম (মুসাফির নয়) মুসলিমের উপর ফরজ।',
        explanationEn: 'Fasting is obligatory upon adult, sane, and healthy Muslims who are not traveling.',
        category: 'fiqh', difficulty: 'easy',
    },
    {
        questionBn: 'যাকাত ফরজ হওয়ার নিসাব (ন্যূনতম পরিমাণ) — সোনার ক্ষেত্রে কত তোলা?',
        questionEn: 'The Nisab (minimum threshold) for Zakat on gold is how many tola?',
        optionsBn: ['৫ তোলা', '৭.৫ তোলা', '৫২.৫ তোলা', '৮৫ গ্রাম'],
        optionsEn: ['5 tola', '7.5 tola', '52.5 tola', '85 grams'],
        correctIndex: 1,
        explanationBn: 'সোনার নিসাব ৭.৫ তোলা বা প্রায় ৮৫ গ্রাম। এই পরিমাণ ১ বছর থাকলে যাকাত দিতে হবে।',
        explanationEn: 'The Nisab for gold is 7.5 tola (approx. 85 grams). If held for a lunar year, Zakat is due.',
        category: 'fiqh', difficulty: 'hard',
    },
    {
        questionBn: 'নামাজে সিজদা কতবার দিতে হয় (প্রতি রাকাতে)?',
        questionEn: 'How many times is Sujood (prostration) performed per Rakat?',
        optionsBn: ['১ বার', '২ বার', '৩ বার', '৪ বার'],
        optionsEn: ['1 time', '2 times', '3 times', '4 times'],
        correctIndex: 1,
        explanationBn: 'প্রতি রাকাতে ২টি সিজদা দিতে হয়।',
        explanationEn: '2 prostrations (Sujood) are performed per Rakat.',
        category: 'fiqh', difficulty: 'easy',
    },
    {
        questionBn: 'হজ ফরজ কার উপর?',
        questionEn: 'Upon whom is Hajj obligatory?',
        optionsBn: ['প্রতিটি মুসলিমের উপর', 'সামর্থ্যবান প্রতিটি মুসলিমের উপর', 'শুধু পুরুষের উপর', 'শুধু ধনী মুসলিমের উপর'],
        optionsEn: ['Every Muslim', 'Every capable Muslim', 'Men only', 'Rich Muslims only'],
        correctIndex: 1,
        explanationBn: 'হজ সামর্থ্যবান (শারীরিক ও আর্থিকভাবে) প্রতিটি মুসলিমের উপর জীবনে একবার ফরজ।',
        explanationEn: 'Hajj is obligatory once in a lifetime for every Muslim who is physically and financially capable.',
        category: 'fiqh', difficulty: 'easy',
    },
    {
        questionBn: 'ওজু ভেঙে যায় কোনটিতে?',
        questionEn: 'Which of the following invalidates (breaks) Wudu?',
        optionsBn: ['হাত ধোয়া', 'ঘুমানো', 'কান্না করা', 'জোরে হাসা'],
        optionsEn: ['Washing hands', 'Sleeping', 'Crying', 'Laughing loudly'],
        correctIndex: 1,
        explanationBn: 'ঘুমানোর ফলে ওজু ভেঙে যায়, কারণ ঘুমের সময় সংজ্ঞা হারিয়ে যায়।',
        explanationEn: 'Sleeping breaks Wudu because consciousness is lost during sleep.',
        category: 'fiqh', difficulty: 'normal',
    },
    {
        questionBn: 'জুমার নামাজ কত রাকাত ফরজ?',
        questionEn: 'How many Rakat is the obligatory (Fard) Jumu\'ah prayer?',
        optionsBn: ['২', '৪', '৬', '৮'],
        optionsEn: ['2', '4', '6', '8'],
        correctIndex: 0,
        explanationBn: 'জুমার ফরজ নামাজ ২ রাকাত — দুটি খুতবার পরে পড়া হয়।',
        explanationEn: 'The obligatory Jumu\'ah prayer is 2 Rakat, performed after two khutbahs.',
        category: 'fiqh', difficulty: 'easy',
    },
    {
        questionBn: 'কোন রোজা রাখা হারাম?',
        questionEn: 'On which day is it Haram (forbidden) to fast?',
        optionsBn: ['সোমবার', 'ঈদুল ফিতরের দিন', 'আশুরার দিন', 'আরাফার দিন'],
        optionsEn: ['Monday', 'Day of Eid al-Fitr', 'Day of Ashura', 'Day of Arafah'],
        correctIndex: 1,
        explanationBn: 'ঈদুল ফিতর ও ঈদুল আযহার দিন রোজা রাখা হারাম।',
        explanationEn: 'Fasting on Eid al-Fitr and Eid al-Adha is forbidden (Haram).',
        category: 'fiqh', difficulty: 'normal',
    },
    {
        questionBn: 'তায়াম্মুমের বিকল্প হিসেবে কী ব্যবহার করা হয়?',
        questionEn: 'What is used as a substitute in Tayammum?',
        optionsBn: ['পাথর', 'মাটি বা ধুলো', 'বালু', 'ছাই'],
        optionsEn: ['Stone', 'Earth or dust', 'Sand', 'Ash'],
        correctIndex: 1,
        explanationBn: 'তায়াম্মুমে পানির বিকল্প হিসেবে পবিত্র মাটি বা ধুলো ব্যবহার করা হয়।',
        explanationEn: 'In Tayammum, pure earth or dust is used as a substitute for water.',
        category: 'fiqh', difficulty: 'normal',
    },
    {
        questionBn: 'কুরআন অনুযায়ী যাকাত কত শ্রেণীর মানুষ পাবে?',
        questionEn: 'According to the Quran, Zakat is distributed among how many categories?',
        optionsBn: ['৪', '৬', '৮', '১০'],
        optionsEn: ['4', '6', '8', '10'],
        correctIndex: 2,
        explanationBn: 'সূরা তওবার ৬০ নম্বর আয়াত অনুযায়ী যাকাতের ৮টি খাত আছে।',
        explanationEn: 'According to Surah Tawbah 9:60, Zakat has 8 categories of recipients.',
        category: 'fiqh', difficulty: 'boss',
    },

    // ─── GENERAL (10 questions) ────────────────────────────────────────────
    {
        questionBn: 'মসজিদুল হারাম কোন শহরে অবস্থিত?',
        questionEn: 'In which city is Masjid al-Haram located?',
        optionsBn: ['মদিনা', 'মক্কা', 'জেরুজালেম', 'তাইফ'],
        optionsEn: ['Madinah', 'Makkah', 'Jerusalem', 'Taif'],
        correctIndex: 1,
        explanationBn: 'মসজিদুল হারাম সৌদি আরবের মক্কায় অবস্থিত — এটি পৃথিবীর সবচেয়ে বড় মসজিদ।',
        explanationEn: 'Masjid al-Haram is located in Makkah, Saudi Arabia — it is the largest mosque in the world.',
        category: 'general', difficulty: 'easy',
    },
    {
        questionBn: 'ইসলামের প্রথম মসজিদ কোনটি?',
        questionEn: 'Which was the first mosque in Islam?',
        optionsBn: ['মসজিদুল হারাম', 'মসজিদে নববি', 'মসজিদে আকসা', 'মসজিদে কুবা'],
        optionsEn: ['Masjid al-Haram', 'Masjid al-Nabawi', 'Masjid al-Aqsa', 'Masjid Quba'],
        correctIndex: 3,
        explanationBn: 'মসজিদে কুবা ইসলামের প্রথম মসজিদ, যা নবী (ﷺ) মদিনায় হিজরতের সময় নির্মাণ করেন।',
        explanationEn: 'Masjid Quba is the first mosque in Islam, built by the Prophet (ﷺ) during his migration to Madinah.',
        category: 'general', difficulty: 'normal',
    },
    {
        questionBn: 'কাবা শরিফ প্রথম কে নির্মাণ করেন?',
        questionEn: 'Who first built the Kaaba?',
        optionsBn: ['নবী মুহাম্মদ (ﷺ)', 'নবী ইব্রাহিম (আ)', 'নবী আদম (আ)', 'নবী নূহ (আ)'],
        optionsEn: ['Prophet Muhammad (ﷺ)', 'Prophet Ibrahim (AS)', 'Prophet Adam (AS)', 'Prophet Nuh (AS)'],
        correctIndex: 1,
        explanationBn: 'কুরআন অনুযায়ী নবী ইব্রাহিম (আ) ও তাঁর পুত্র ইসমাইল (আ) মিলে কাবা নির্মাণ করেন।',
        explanationEn: 'According to the Quran, Prophet Ibrahim (AS) and his son Ismail (AS) built the Kaaba.',
        category: 'general', difficulty: 'easy',
    },
    {
        questionBn: 'ইসলামিক ক্যালেন্ডারের প্রথম মাস কোনটি?',
        questionEn: 'Which is the first month of the Islamic calendar?',
        optionsBn: ['রমজান', 'শাওয়াল', 'মুহাররম', 'রজব'],
        optionsEn: ['Ramadan', 'Shawwal', 'Muharram', 'Rajab'],
        correctIndex: 2,
        explanationBn: 'মুহাররম হল ইসলামিক হিজরি ক্যালেন্ডারের প্রথম মাস।',
        explanationEn: 'Muharram is the first month of the Islamic Hijri calendar.',
        category: 'general', difficulty: 'easy',
    },
    {
        questionBn: 'মুসলিম বিশ্বের কোন দেশে সবচেয়ে বেশি মুসলিম জনসংখ্যা?',
        questionEn: 'Which country has the largest Muslim population?',
        optionsBn: ['সৌদি আরব', 'পাকিস্তান', 'ইন্দোনেশিয়া', 'বাংলাদেশ'],
        optionsEn: ['Saudi Arabia', 'Pakistan', 'Indonesia', 'Bangladesh'],
        correctIndex: 2,
        explanationBn: 'ইন্দোনেশিয়ায় বিশ্বের সবচেয়ে বেশি মুসলিম বাস করে — প্রায় ২৩ কোটি।',
        explanationEn: 'Indonesia has the largest Muslim population in the world — approximately 230 million.',
        category: 'general', difficulty: 'normal',
    },
    {
        questionBn: 'লাইলাতুল কদর কোন মাসে?',
        questionEn: 'In which month is Laylatul Qadr (Night of Power)?',
        optionsBn: ['রজব', 'শাবান', 'রমজান', 'মুহাররম'],
        optionsEn: ['Rajab', 'Shaban', 'Ramadan', 'Muharram'],
        correctIndex: 2,
        explanationBn: 'লাইলাতুল কদর রমজান মাসের শেষ দশদিনের বেজোড় রাতগুলোতে খোঁজা হয়।',
        explanationEn: 'Laylatul Qadr is sought in the odd nights of the last 10 days of Ramadan.',
        category: 'general', difficulty: 'easy',
    },
    {
        questionBn: 'আরাফাতের দিন কোন তারিখ?',
        questionEn: 'The Day of Arafah falls on which date of Dhul Hijjah?',
        optionsBn: ['৮ তারিখ', '৯ তারিখ', '১০ তারিখ', '১২ তারিখ'],
        optionsEn: ['8th', '9th', '10th', '12th'],
        correctIndex: 1,
        explanationBn: 'আরাফাতের দিন জিলহজ মাসের ৯ তারিখ — এটি হজের সবচেয়ে গুরুত্বপূর্ণ দিন।',
        explanationEn: 'The Day of Arafah is the 9th of Dhul Hijjah — the most important day of Hajj.',
        category: 'general', difficulty: 'normal',
    },
    {
        questionBn: '"আল-আমিন" উপাধি কার ছিল?',
        questionEn: 'Who was given the title "Al-Amin" (The Trustworthy)?',
        optionsBn: ['আবু বকর (রা)', 'উমর (রা)', 'নবী মুহাম্মদ (ﷺ)', 'উসমান (রা)'],
        optionsEn: ['Abu Bakr (RA)', 'Umar (RA)', 'Prophet Muhammad (ﷺ)', 'Uthman (RA)'],
        correctIndex: 2,
        explanationBn: 'নবুওয়াত লাভের আগেও নবী মুহাম্মদ (ﷺ) কে মক্কাবাসী "আল-আমিন" বলে ডাকত।',
        explanationEn: 'Even before prophethood, the people of Makkah called Muhammad (ﷺ) "Al-Amin" (The Trustworthy).',
        category: 'general', difficulty: 'easy',
    },
    {
        questionBn: 'ইসলামে চার খলিফার মধ্যে শেষ খলিফা কে?',
        questionEn: 'Who was the last of the four Rightly-Guided Caliphs?',
        optionsBn: ['উমর (রা)', 'উসমান (রা)', 'আলি (রা)', 'মুয়াবিয়া (রা)'],
        optionsEn: ['Umar (RA)', 'Uthman (RA)', 'Ali (RA)', 'Muawiyah (RA)'],
        correctIndex: 2,
        explanationBn: 'চার রাশিদুন খলিফার মধ্যে সর্বশেষ হলেন আলি ইবনে আবি তালিব (রা)।',
        explanationEn: 'Ali ibn Abi Talib (RA) was the last of the four Rightly-Guided Caliphs.',
        category: 'general', difficulty: 'normal',
    },
    {
        questionBn: 'ইসলামের কোন শাসনামলে "বায়তুল হিকমাহ" (জ্ঞানের ঘর) প্রতিষ্ঠিত হয়?',
        questionEn: 'During which Islamic era was Bayt al-Hikmah (House of Wisdom) established?',
        optionsBn: ['উমাইয়া খিলাফত', 'আব্বাসীয় খিলাফত', 'ফাতিমীয় খিলাফত', 'উসমানীয় সাম্রাজ্য'],
        optionsEn: ['Umayyad Caliphate', 'Abbasid Caliphate', 'Fatimid Caliphate', 'Ottoman Empire'],
        correctIndex: 1,
        explanationBn: 'বায়তুল হিকমাহ আব্বাসীয় খিলাফতের আমলে বাগদাদে প্রতিষ্ঠিত হয়, যেখানে গ্রিক ও পারসিক জ্ঞান আরবিতে অনুবাদ করা হয়।',
        explanationEn: 'Bayt al-Hikmah was established in Baghdad during the Abbasid Caliphate, where Greek and Persian knowledge was translated into Arabic.',
        category: 'general', difficulty: 'boss',
    },
];

async function main() {
    console.log('🌱 Seeding quiz questions...');

    await prisma.quizQuestion.createMany({
        data: questions.map((q) => ({
            questionBn: q.questionBn,
            questionEn: q.questionEn,
            optionsBn: q.optionsBn,
            optionsEn: q.optionsEn,
            correctIndex: q.correctIndex,
            explanationBn: q.explanationBn,
            explanationEn: q.explanationEn,
            category: q.category,
            difficulty: q.difficulty,
            isActive: true,
        })),
        skipDuplicates: false, // allow re-run to add new questions
    });

    const count = await prisma.quizQuestion.count();
    console.log(`✅ Done! Total quiz questions in DB: ${count}`);
}

main()
    .catch((e) => { console.error('Seed error:', e); process.exit(1); })
    .finally(() => prisma.$disconnect());
